//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add Extensions\MyQuantityExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyQuantity.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;

// Windows Runtime Component does not support extension methods and method overloads: https://msdn.microsoft.com/en-us/library/br230301.aspx
#if !WINDOWS_UWP
namespace UnitsNet.Extensions.NumberToLiquidRate
{
    public static class NumberToLiquidRateExtensions
    {
        #region CubicKiloMetersPerDay

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicKiloMetersPerDay(this int value) => LiquidRate.FromCubicKiloMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicKiloMetersPerDay(this int? value) => LiquidRate.FromCubicKiloMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicKiloMetersPerDay(this long value) => LiquidRate.FromCubicKiloMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicKiloMetersPerDay(this long? value) => LiquidRate.FromCubicKiloMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicKiloMetersPerDay(this double value) => LiquidRate.FromCubicKiloMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicKiloMetersPerDay(this double? value) => LiquidRate.FromCubicKiloMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicKiloMetersPerDay(this float value) => LiquidRate.FromCubicKiloMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicKiloMetersPerDay(this float? value) => LiquidRate.FromCubicKiloMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicKiloMetersPerDay(this decimal value) => LiquidRate.FromCubicKiloMetersPerDay(Convert.ToDouble(value));

        /// <inheritdoc cref="LiquidRate.FromCubicKiloMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicKiloMetersPerDay(this decimal? value) => LiquidRate.FromCubicKiloMetersPerDay(value == null ? (double?)null : Convert.ToDouble(value.Value));

        #endregion

        #region CubicMeterPerDay

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicMetersPerDay(this int value) => LiquidRate.FromCubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicMetersPerDay(this int? value) => LiquidRate.FromCubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicMetersPerDay(this long value) => LiquidRate.FromCubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicMetersPerDay(this long? value) => LiquidRate.FromCubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicMetersPerDay(this double value) => LiquidRate.FromCubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicMetersPerDay(this double? value) => LiquidRate.FromCubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicMetersPerDay(this float value) => LiquidRate.FromCubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicMetersPerDay(this float? value) => LiquidRate.FromCubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate CubicMetersPerDay(this decimal value) => LiquidRate.FromCubicMetersPerDay(Convert.ToDouble(value));

        /// <inheritdoc cref="LiquidRate.FromCubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? CubicMetersPerDay(this decimal? value) => LiquidRate.FromCubicMetersPerDay(value == null ? (double?)null : Convert.ToDouble(value.Value));

        #endregion

        #region HectocubicMeterPerDay

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate HectocubicMetersPerDay(this int value) => LiquidRate.FromHectocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? HectocubicMetersPerDay(this int? value) => LiquidRate.FromHectocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate HectocubicMetersPerDay(this long value) => LiquidRate.FromHectocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? HectocubicMetersPerDay(this long? value) => LiquidRate.FromHectocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate HectocubicMetersPerDay(this double value) => LiquidRate.FromHectocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? HectocubicMetersPerDay(this double? value) => LiquidRate.FromHectocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate HectocubicMetersPerDay(this float value) => LiquidRate.FromHectocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? HectocubicMetersPerDay(this float? value) => LiquidRate.FromHectocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate HectocubicMetersPerDay(this decimal value) => LiquidRate.FromHectocubicMetersPerDay(Convert.ToDouble(value));

        /// <inheritdoc cref="LiquidRate.FromHectocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? HectocubicMetersPerDay(this decimal? value) => LiquidRate.FromHectocubicMetersPerDay(value == null ? (double?)null : Convert.ToDouble(value.Value));

        #endregion

        #region KilocubicMeterPerDay

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate KilocubicMetersPerDay(this int value) => LiquidRate.FromKilocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? KilocubicMetersPerDay(this int? value) => LiquidRate.FromKilocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate KilocubicMetersPerDay(this long value) => LiquidRate.FromKilocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? KilocubicMetersPerDay(this long? value) => LiquidRate.FromKilocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate KilocubicMetersPerDay(this double value) => LiquidRate.FromKilocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? KilocubicMetersPerDay(this double? value) => LiquidRate.FromKilocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate KilocubicMetersPerDay(this float value) => LiquidRate.FromKilocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? KilocubicMetersPerDay(this float? value) => LiquidRate.FromKilocubicMetersPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate KilocubicMetersPerDay(this decimal value) => LiquidRate.FromKilocubicMetersPerDay(Convert.ToDouble(value));

        /// <inheritdoc cref="LiquidRate.FromKilocubicMetersPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? KilocubicMetersPerDay(this decimal? value) => LiquidRate.FromKilocubicMetersPerDay(value == null ? (double?)null : Convert.ToDouble(value.Value));

        #endregion

        #region MillionOilBarrelPerDay

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate MillionOilBarrelsPerDay(this int value) => LiquidRate.FromMillionOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? MillionOilBarrelsPerDay(this int? value) => LiquidRate.FromMillionOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate MillionOilBarrelsPerDay(this long value) => LiquidRate.FromMillionOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? MillionOilBarrelsPerDay(this long? value) => LiquidRate.FromMillionOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate MillionOilBarrelsPerDay(this double value) => LiquidRate.FromMillionOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? MillionOilBarrelsPerDay(this double? value) => LiquidRate.FromMillionOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate MillionOilBarrelsPerDay(this float value) => LiquidRate.FromMillionOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? MillionOilBarrelsPerDay(this float? value) => LiquidRate.FromMillionOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate MillionOilBarrelsPerDay(this decimal value) => LiquidRate.FromMillionOilBarrelsPerDay(Convert.ToDouble(value));

        /// <inheritdoc cref="LiquidRate.FromMillionOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? MillionOilBarrelsPerDay(this decimal? value) => LiquidRate.FromMillionOilBarrelsPerDay(value == null ? (double?)null : Convert.ToDouble(value.Value));

        #endregion

        #region OilBarrelsPerDay

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate OilBarrelsPerDay(this int value) => LiquidRate.FromOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? OilBarrelsPerDay(this int? value) => LiquidRate.FromOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate OilBarrelsPerDay(this long value) => LiquidRate.FromOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? OilBarrelsPerDay(this long? value) => LiquidRate.FromOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate OilBarrelsPerDay(this double value) => LiquidRate.FromOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? OilBarrelsPerDay(this double? value) => LiquidRate.FromOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate OilBarrelsPerDay(this float value) => LiquidRate.FromOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? OilBarrelsPerDay(this float? value) => LiquidRate.FromOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate OilBarrelsPerDay(this decimal value) => LiquidRate.FromOilBarrelsPerDay(Convert.ToDouble(value));

        /// <inheritdoc cref="LiquidRate.FromOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? OilBarrelsPerDay(this decimal? value) => LiquidRate.FromOilBarrelsPerDay(value == null ? (double?)null : Convert.ToDouble(value.Value));

        #endregion

        #region ThousandOilBarrelsPerDay

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate ThousandOilBarrelsPerDay(this int value) => LiquidRate.FromThousandOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? ThousandOilBarrelsPerDay(this int? value) => LiquidRate.FromThousandOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate ThousandOilBarrelsPerDay(this long value) => LiquidRate.FromThousandOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? ThousandOilBarrelsPerDay(this long? value) => LiquidRate.FromThousandOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate ThousandOilBarrelsPerDay(this double value) => LiquidRate.FromThousandOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? ThousandOilBarrelsPerDay(this double? value) => LiquidRate.FromThousandOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate ThousandOilBarrelsPerDay(this float value) => LiquidRate.FromThousandOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? ThousandOilBarrelsPerDay(this float? value) => LiquidRate.FromThousandOilBarrelsPerDay(value);

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate ThousandOilBarrelsPerDay(this decimal value) => LiquidRate.FromThousandOilBarrelsPerDay(Convert.ToDouble(value));

        /// <inheritdoc cref="LiquidRate.FromThousandOilBarrelsPerDay(UnitsNet.QuantityValue)" />
        public static LiquidRate? ThousandOilBarrelsPerDay(this decimal? value) => LiquidRate.FromThousandOilBarrelsPerDay(value == null ? (double?)null : Convert.ToDouble(value.Value));

        #endregion

    }
}
#endif
