//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add Extensions\MyQuantityExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyQuantity.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using UnitsNet.Units;
using Xunit;

// Disable build warning CS1718: Comparison made to same variable; did you mean to compare something else?
#pragma warning disable 1718

// ReSharper disable once CheckNamespace
namespace UnitsNet.Tests
{
    /// <summary>
    /// Test of GasRate.
    /// </summary>
// ReSharper disable once PartialTypeWithSinglePart
    public abstract partial class GasRateTestsBase
    {
        protected abstract double CubicFeetInOneCubicMeterPerDay { get; }
        protected abstract double CubicMetersPerDayInOneCubicMeterPerDay { get; }
        protected abstract double GigacubicFeetInOneCubicMeterPerDay { get; }
        protected abstract double HectocubicMetersPerDayInOneCubicMeterPerDay { get; }
        protected abstract double KilocubicFeetInOneCubicMeterPerDay { get; }
        protected abstract double KilocubicMetersPerDayInOneCubicMeterPerDay { get; }
        protected abstract double MegacubicFeetInOneCubicMeterPerDay { get; }
        protected abstract double MegacubicMetersPerDayInOneCubicMeterPerDay { get; }
        protected abstract double TeracubicFeetInOneCubicMeterPerDay { get; }

// ReSharper disable VirtualMemberNeverOverriden.Global
        protected virtual double CubicFeetTolerance { get { return 1e-5; } }
        protected virtual double CubicMetersPerDayTolerance { get { return 1e-5; } }
        protected virtual double GigacubicFeetTolerance { get { return 1e-5; } }
        protected virtual double HectocubicMetersPerDayTolerance { get { return 1e-5; } }
        protected virtual double KilocubicFeetTolerance { get { return 1e-5; } }
        protected virtual double KilocubicMetersPerDayTolerance { get { return 1e-5; } }
        protected virtual double MegacubicFeetTolerance { get { return 1e-5; } }
        protected virtual double MegacubicMetersPerDayTolerance { get { return 1e-5; } }
        protected virtual double TeracubicFeetTolerance { get { return 1e-5; } }
// ReSharper restore VirtualMemberNeverOverriden.Global

        [Fact]
        public void CubicMeterPerDayToGasRateUnits()
        {
            GasRate cubicmeterperday = GasRate.FromCubicMetersPerDay(1);
            AssertEx.EqualTolerance(CubicFeetInOneCubicMeterPerDay, cubicmeterperday.CubicFeet, CubicFeetTolerance);
            AssertEx.EqualTolerance(CubicMetersPerDayInOneCubicMeterPerDay, cubicmeterperday.CubicMetersPerDay, CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(GigacubicFeetInOneCubicMeterPerDay, cubicmeterperday.GigacubicFeet, GigacubicFeetTolerance);
            AssertEx.EqualTolerance(HectocubicMetersPerDayInOneCubicMeterPerDay, cubicmeterperday.HectocubicMetersPerDay, HectocubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(KilocubicFeetInOneCubicMeterPerDay, cubicmeterperday.KilocubicFeet, KilocubicFeetTolerance);
            AssertEx.EqualTolerance(KilocubicMetersPerDayInOneCubicMeterPerDay, cubicmeterperday.KilocubicMetersPerDay, KilocubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(MegacubicFeetInOneCubicMeterPerDay, cubicmeterperday.MegacubicFeet, MegacubicFeetTolerance);
            AssertEx.EqualTolerance(MegacubicMetersPerDayInOneCubicMeterPerDay, cubicmeterperday.MegacubicMetersPerDay, MegacubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(TeracubicFeetInOneCubicMeterPerDay, cubicmeterperday.TeracubicFeet, TeracubicFeetTolerance);
        }

        [Fact]
        public void FromValueAndUnit()
        {
            AssertEx.EqualTolerance(1, GasRate.From(1, GasRateUnit.CubicFoot).CubicFeet, CubicFeetTolerance);
            AssertEx.EqualTolerance(1, GasRate.From(1, GasRateUnit.CubicMeterPerDay).CubicMetersPerDay, CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(1, GasRate.From(1, GasRateUnit.GigacubicFoot).GigacubicFeet, GigacubicFeetTolerance);
            AssertEx.EqualTolerance(1, GasRate.From(1, GasRateUnit.HectocubicMeterPerDay).HectocubicMetersPerDay, HectocubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(1, GasRate.From(1, GasRateUnit.KilocubicFoot).KilocubicFeet, KilocubicFeetTolerance);
            AssertEx.EqualTolerance(1, GasRate.From(1, GasRateUnit.KilocubicMeterPerDay).KilocubicMetersPerDay, KilocubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(1, GasRate.From(1, GasRateUnit.MegacubicFoot).MegacubicFeet, MegacubicFeetTolerance);
            AssertEx.EqualTolerance(1, GasRate.From(1, GasRateUnit.MegacubicMeterPerDay).MegacubicMetersPerDay, MegacubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(1, GasRate.From(1, GasRateUnit.TeracubicFoot).TeracubicFeet, TeracubicFeetTolerance);
        }

        [Fact]
        public void As()
        {
            var cubicmeterperday = GasRate.FromCubicMetersPerDay(1);
            AssertEx.EqualTolerance(CubicFeetInOneCubicMeterPerDay, cubicmeterperday.As(GasRateUnit.CubicFoot), CubicFeetTolerance);
            AssertEx.EqualTolerance(CubicMetersPerDayInOneCubicMeterPerDay, cubicmeterperday.As(GasRateUnit.CubicMeterPerDay), CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(GigacubicFeetInOneCubicMeterPerDay, cubicmeterperday.As(GasRateUnit.GigacubicFoot), GigacubicFeetTolerance);
            AssertEx.EqualTolerance(HectocubicMetersPerDayInOneCubicMeterPerDay, cubicmeterperday.As(GasRateUnit.HectocubicMeterPerDay), HectocubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(KilocubicFeetInOneCubicMeterPerDay, cubicmeterperday.As(GasRateUnit.KilocubicFoot), KilocubicFeetTolerance);
            AssertEx.EqualTolerance(KilocubicMetersPerDayInOneCubicMeterPerDay, cubicmeterperday.As(GasRateUnit.KilocubicMeterPerDay), KilocubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(MegacubicFeetInOneCubicMeterPerDay, cubicmeterperday.As(GasRateUnit.MegacubicFoot), MegacubicFeetTolerance);
            AssertEx.EqualTolerance(MegacubicMetersPerDayInOneCubicMeterPerDay, cubicmeterperday.As(GasRateUnit.MegacubicMeterPerDay), MegacubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(TeracubicFeetInOneCubicMeterPerDay, cubicmeterperday.As(GasRateUnit.TeracubicFoot), TeracubicFeetTolerance);
        }

        [Fact]
        public void ToUnit()
        {
            var cubicmeterperday = GasRate.FromCubicMetersPerDay(1);

            var cubicfootQuantity = cubicmeterperday.ToUnit(GasRateUnit.CubicFoot);
            AssertEx.EqualTolerance(CubicFeetInOneCubicMeterPerDay, (double)cubicfootQuantity.Value, CubicFeetTolerance);
            Assert.Equal(GasRateUnit.CubicFoot, cubicfootQuantity.Unit);

            var cubicmeterperdayQuantity = cubicmeterperday.ToUnit(GasRateUnit.CubicMeterPerDay);
            AssertEx.EqualTolerance(CubicMetersPerDayInOneCubicMeterPerDay, (double)cubicmeterperdayQuantity.Value, CubicMetersPerDayTolerance);
            Assert.Equal(GasRateUnit.CubicMeterPerDay, cubicmeterperdayQuantity.Unit);

            var gigacubicfootQuantity = cubicmeterperday.ToUnit(GasRateUnit.GigacubicFoot);
            AssertEx.EqualTolerance(GigacubicFeetInOneCubicMeterPerDay, (double)gigacubicfootQuantity.Value, GigacubicFeetTolerance);
            Assert.Equal(GasRateUnit.GigacubicFoot, gigacubicfootQuantity.Unit);

            var hectocubicmeterperdayQuantity = cubicmeterperday.ToUnit(GasRateUnit.HectocubicMeterPerDay);
            AssertEx.EqualTolerance(HectocubicMetersPerDayInOneCubicMeterPerDay, (double)hectocubicmeterperdayQuantity.Value, HectocubicMetersPerDayTolerance);
            Assert.Equal(GasRateUnit.HectocubicMeterPerDay, hectocubicmeterperdayQuantity.Unit);

            var kilocubicfootQuantity = cubicmeterperday.ToUnit(GasRateUnit.KilocubicFoot);
            AssertEx.EqualTolerance(KilocubicFeetInOneCubicMeterPerDay, (double)kilocubicfootQuantity.Value, KilocubicFeetTolerance);
            Assert.Equal(GasRateUnit.KilocubicFoot, kilocubicfootQuantity.Unit);

            var kilocubicmeterperdayQuantity = cubicmeterperday.ToUnit(GasRateUnit.KilocubicMeterPerDay);
            AssertEx.EqualTolerance(KilocubicMetersPerDayInOneCubicMeterPerDay, (double)kilocubicmeterperdayQuantity.Value, KilocubicMetersPerDayTolerance);
            Assert.Equal(GasRateUnit.KilocubicMeterPerDay, kilocubicmeterperdayQuantity.Unit);

            var megacubicfootQuantity = cubicmeterperday.ToUnit(GasRateUnit.MegacubicFoot);
            AssertEx.EqualTolerance(MegacubicFeetInOneCubicMeterPerDay, (double)megacubicfootQuantity.Value, MegacubicFeetTolerance);
            Assert.Equal(GasRateUnit.MegacubicFoot, megacubicfootQuantity.Unit);

            var megacubicmeterperdayQuantity = cubicmeterperday.ToUnit(GasRateUnit.MegacubicMeterPerDay);
            AssertEx.EqualTolerance(MegacubicMetersPerDayInOneCubicMeterPerDay, (double)megacubicmeterperdayQuantity.Value, MegacubicMetersPerDayTolerance);
            Assert.Equal(GasRateUnit.MegacubicMeterPerDay, megacubicmeterperdayQuantity.Unit);

            var teracubicfootQuantity = cubicmeterperday.ToUnit(GasRateUnit.TeracubicFoot);
            AssertEx.EqualTolerance(TeracubicFeetInOneCubicMeterPerDay, (double)teracubicfootQuantity.Value, TeracubicFeetTolerance);
            Assert.Equal(GasRateUnit.TeracubicFoot, teracubicfootQuantity.Unit);
        }

        [Fact]
        public void ConversionRoundTrip()
        {
            GasRate cubicmeterperday = GasRate.FromCubicMetersPerDay(1);
            AssertEx.EqualTolerance(1, GasRate.FromCubicFeet(cubicmeterperday.CubicFeet).CubicMetersPerDay, CubicFeetTolerance);
            AssertEx.EqualTolerance(1, GasRate.FromCubicMetersPerDay(cubicmeterperday.CubicMetersPerDay).CubicMetersPerDay, CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(1, GasRate.FromGigacubicFeet(cubicmeterperday.GigacubicFeet).CubicMetersPerDay, GigacubicFeetTolerance);
            AssertEx.EqualTolerance(1, GasRate.FromHectocubicMetersPerDay(cubicmeterperday.HectocubicMetersPerDay).CubicMetersPerDay, HectocubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(1, GasRate.FromKilocubicFeet(cubicmeterperday.KilocubicFeet).CubicMetersPerDay, KilocubicFeetTolerance);
            AssertEx.EqualTolerance(1, GasRate.FromKilocubicMetersPerDay(cubicmeterperday.KilocubicMetersPerDay).CubicMetersPerDay, KilocubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(1, GasRate.FromMegacubicFeet(cubicmeterperday.MegacubicFeet).CubicMetersPerDay, MegacubicFeetTolerance);
            AssertEx.EqualTolerance(1, GasRate.FromMegacubicMetersPerDay(cubicmeterperday.MegacubicMetersPerDay).CubicMetersPerDay, MegacubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(1, GasRate.FromTeracubicFeet(cubicmeterperday.TeracubicFeet).CubicMetersPerDay, TeracubicFeetTolerance);
        }

        [Fact]
        public void ArithmeticOperators()
        {
            GasRate v = GasRate.FromCubicMetersPerDay(1);
            AssertEx.EqualTolerance(-1, -v.CubicMetersPerDay, CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(2, (GasRate.FromCubicMetersPerDay(3)-v).CubicMetersPerDay, CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(2, (v + v).CubicMetersPerDay, CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(10, (v*10).CubicMetersPerDay, CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(10, (10*v).CubicMetersPerDay, CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(2, (GasRate.FromCubicMetersPerDay(10)/5).CubicMetersPerDay, CubicMetersPerDayTolerance);
            AssertEx.EqualTolerance(2, GasRate.FromCubicMetersPerDay(10)/GasRate.FromCubicMetersPerDay(5), CubicMetersPerDayTolerance);
        }

        [Fact]
        public void ComparisonOperators()
        {
            GasRate oneCubicMeterPerDay = GasRate.FromCubicMetersPerDay(1);
            GasRate twoCubicMetersPerDay = GasRate.FromCubicMetersPerDay(2);

            Assert.True(oneCubicMeterPerDay < twoCubicMetersPerDay);
            Assert.True(oneCubicMeterPerDay <= twoCubicMetersPerDay);
            Assert.True(twoCubicMetersPerDay > oneCubicMeterPerDay);
            Assert.True(twoCubicMetersPerDay >= oneCubicMeterPerDay);

            Assert.False(oneCubicMeterPerDay > twoCubicMetersPerDay);
            Assert.False(oneCubicMeterPerDay >= twoCubicMetersPerDay);
            Assert.False(twoCubicMetersPerDay < oneCubicMeterPerDay);
            Assert.False(twoCubicMetersPerDay <= oneCubicMeterPerDay);
        }

        [Fact]
        public void CompareToIsImplemented()
        {
            GasRate cubicmeterperday = GasRate.FromCubicMetersPerDay(1);
            Assert.Equal(0, cubicmeterperday.CompareTo(cubicmeterperday));
            Assert.True(cubicmeterperday.CompareTo(GasRate.Zero) > 0);
            Assert.True(GasRate.Zero.CompareTo(cubicmeterperday) < 0);
        }

        [Fact]
        public void CompareToThrowsOnTypeMismatch()
        {
            GasRate cubicmeterperday = GasRate.FromCubicMetersPerDay(1);
            Assert.Throws<ArgumentException>(() => cubicmeterperday.CompareTo(new object()));
        }

        [Fact]
        public void CompareToThrowsOnNull()
        {
            GasRate cubicmeterperday = GasRate.FromCubicMetersPerDay(1);
            Assert.Throws<ArgumentNullException>(() => cubicmeterperday.CompareTo(null));
        }


        [Fact]
        public void EqualityOperators()
        {
            GasRate a = GasRate.FromCubicMetersPerDay(1);
            GasRate b = GasRate.FromCubicMetersPerDay(2);

// ReSharper disable EqualExpressionComparison
            Assert.True(a == a);
            Assert.True(a != b);

            Assert.False(a == b);
            Assert.False(a != a);
// ReSharper restore EqualExpressionComparison
        }

        [Fact]
        public void EqualsIsImplemented()
        {
            GasRate v = GasRate.FromCubicMetersPerDay(1);
            Assert.True(v.Equals(GasRate.FromCubicMetersPerDay(1), GasRate.FromCubicMetersPerDay(CubicMetersPerDayTolerance)));
            Assert.False(v.Equals(GasRate.Zero, GasRate.FromCubicMetersPerDay(CubicMetersPerDayTolerance)));
        }

        [Fact]
        public void EqualsReturnsFalseOnTypeMismatch()
        {
            GasRate cubicmeterperday = GasRate.FromCubicMetersPerDay(1);
            Assert.False(cubicmeterperday.Equals(new object()));
        }

        [Fact]
        public void EqualsReturnsFalseOnNull()
        {
            GasRate cubicmeterperday = GasRate.FromCubicMetersPerDay(1);
            Assert.False(cubicmeterperday.Equals(null));
        }
    }
}
