//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by \generate-code.bat.
//
//     Changes to this file will be lost when the code is regenerated.
//     The build server regenerates the code before each build and a pre-build
//     step will regenerate the code on each local build.
//
//     See https://github.com/angularsen/UnitsNet/wiki/Adding-a-New-Unit for how to add or edit units.
//
//     Add CustomCode\Quantities\MyQuantity.extra.cs files to add code to generated quantities.
//     Add Extensions\MyQuantityExtensions.cs to decorate quantities with new behavior.
//     Add UnitDefinitions\MyQuantity.json and run GeneratUnits.bat to generate new units or quantities.
//
// </auto-generated>
//------------------------------------------------------------------------------

// Copyright (c) 2013 Andreas Gullberg Larsen (andreas.larsen84@gmail.com).
// https://github.com/angularsen/UnitsNet
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text.RegularExpressions;
using System.Linq;
using JetBrains.Annotations;
using UnitsNet.Units;

// ReSharper disable once CheckNamespace

namespace UnitsNet
{
    /// <summary>
    ///     GasRate: holds the volume of flowing gas.  This overlaps with the VolumeFlow unit, but provides additional conversions used primarly for O&G Volumes.
    /// </summary>
    // ReSharper disable once PartialTypeWithSinglePart

    // Windows Runtime Component has constraints on public types: https://msdn.microsoft.com/en-us/library/br230301.aspx#Declaring types in Windows Runtime Components
    // Public structures can't have any members other than public fields, and those fields must be value types or strings.
    // Public classes must be sealed (NotInheritable in Visual Basic). If your programming model requires polymorphism, you can create a public interface and implement that interface on the classes that must be polymorphic.
#if WINDOWS_UWP
    public sealed partial class GasRate : IQuantity
#else
    public partial struct GasRate : IQuantity, IComparable, IComparable<GasRate>
#endif
    {
        /// <summary>
        ///     The numeric value this quantity was constructed with.
        /// </summary>
        private readonly double _value;

        /// <summary>
        ///     The unit this quantity was constructed with.
        /// </summary>
        private readonly GasRateUnit? _unit;

        /// <summary>
        ///     The unit this quantity was constructed with -or- <see cref="BaseUnit" /> if default ctor was used.
        /// </summary>
        public GasRateUnit Unit => _unit.GetValueOrDefault(BaseUnit);

        static GasRate()
        {
        }

        [Obsolete("Use the constructor that takes a unit parameter. This constructor will be removed in a future version.")]
        public GasRate(double cubicmetersperday)
        {
            _value = Convert.ToDouble(cubicmetersperday);
            _unit = BaseUnit;
        }

        /// <summary>
        ///     Creates the quantity with the given numeric value and unit.
        /// </summary>
        /// <param name="numericValue">Numeric value.</param>
        /// <param name="unit">Unit representation.</param>
        /// <remarks>Value parameter cannot be named 'value' due to constraint when targeting Windows Runtime Component.</remarks>
#if WINDOWS_UWP
        private
#else
        public 
#endif
        GasRate(double numericValue, GasRateUnit unit)
        {
            _value = numericValue;
            _unit = unit;
        }

        // Windows Runtime Component does not allow public methods/ctors with same number of parameters: https://msdn.microsoft.com/en-us/library/br230301.aspx#Overloaded methods
        /// <summary>
        ///     Creates the quantity with the given value assuming the base unit CubicMeterPerDay.
        /// </summary>
        /// <param name="cubicmetersperday">Value assuming base unit CubicMeterPerDay.</param>
#if WINDOWS_UWP
        private
#else
        [Obsolete("Use the constructor that takes a unit parameter. This constructor will be removed in a future version.")]
        public
#endif
        GasRate(long cubicmetersperday) : this(Convert.ToDouble(cubicmetersperday), BaseUnit) { }

        // Windows Runtime Component does not allow public methods/ctors with same number of parameters: https://msdn.microsoft.com/en-us/library/br230301.aspx#Overloaded methods
        // Windows Runtime Component does not support decimal type
        /// <summary>
        ///     Creates the quantity with the given value assuming the base unit CubicMeterPerDay.
        /// </summary>
        /// <param name="cubicmetersperday">Value assuming base unit CubicMeterPerDay.</param>
#if WINDOWS_UWP
        private
#else
        [Obsolete("Use the constructor that takes a unit parameter. This constructor will be removed in a future version.")]
        public
#endif
        GasRate(decimal cubicmetersperday) : this(Convert.ToDouble(cubicmetersperday), BaseUnit) { }

        #region Properties

        /// <summary>
        ///     The <see cref="QuantityType" /> of this quantity.
        /// </summary>
        public static QuantityType QuantityType => QuantityType.GasRate;

        /// <summary>
        ///     The base unit representation of this quantity for the numeric value stored internally. All conversions go via this value.
        /// </summary>
        public static GasRateUnit BaseUnit => GasRateUnit.CubicMeterPerDay;

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public static BaseDimensions BaseDimensions
        {
            get;
        }

        /// <summary>
        ///     All units of measurement for the GasRate quantity.
        /// </summary>
        public static GasRateUnit[] Units { get; } = Enum.GetValues(typeof(GasRateUnit)).Cast<GasRateUnit>().ToArray();

        /// <summary>
        ///     Get GasRate in BillionCubicFeetPerDay.
        /// </summary>
        public double BillionCubicFeetPerDay => As(GasRateUnit.BillionCubicFootPerDay);

        /// <summary>
        ///     Get GasRate in CubicFeetPerDay.
        /// </summary>
        public double CubicFeetPerDay => As(GasRateUnit.CubicFootPerDay);

        /// <summary>
        ///     Get GasRate in CubicKiloMetersPerDay.
        /// </summary>
        public double CubicKiloMetersPerDay => As(GasRateUnit.CubicKiloMetersPerDay);

        /// <summary>
        ///     Get GasRate in CubicMetersPerDay.
        /// </summary>
        public double CubicMetersPerDay => As(GasRateUnit.CubicMeterPerDay);

        /// <summary>
        ///     Get GasRate in GigacubicFeetPerDay.
        /// </summary>
        public double GigacubicFeetPerDay => As(GasRateUnit.GigacubicFootPerDay);

        /// <summary>
        ///     Get GasRate in HectocubicMetersPerDay.
        /// </summary>
        public double HectocubicMetersPerDay => As(GasRateUnit.HectocubicMeterPerDay);

        /// <summary>
        ///     Get GasRate in KilocubicFeetPerDay.
        /// </summary>
        public double KilocubicFeetPerDay => As(GasRateUnit.KilocubicFootPerDay);

        /// <summary>
        ///     Get GasRate in KilocubicMetersPerDay.
        /// </summary>
        public double KilocubicMetersPerDay => As(GasRateUnit.KilocubicMeterPerDay);

        /// <summary>
        ///     Get GasRate in MegacubicFeetPerDay.
        /// </summary>
        public double MegacubicFeetPerDay => As(GasRateUnit.MegacubicFootPerDay);

        /// <summary>
        ///     Get GasRate in MegacubicMetersPerDay.
        /// </summary>
        public double MegacubicMetersPerDay => As(GasRateUnit.MegacubicMeterPerDay);

        /// <summary>
        ///     Get GasRate in MillionCubicFeetPerDay.
        /// </summary>
        public double MillionCubicFeetPerDay => As(GasRateUnit.MillionCubicFootPerDay);

        /// <summary>
        ///     Get GasRate in TeracubicFeetPerDay.
        /// </summary>
        public double TeracubicFeetPerDay => As(GasRateUnit.TeracubicFootPerDay);

        /// <summary>
        ///     Get GasRate in ThousandCubicFeetPerDay.
        /// </summary>
        public double ThousandCubicFeetPerDay => As(GasRateUnit.ThousandCubicFootPerDay);

        #endregion

        #region Static

        public static GasRate Zero => new GasRate(0, BaseUnit);

        /// <summary>
        ///     Get GasRate from BillionCubicFeetPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromBillionCubicFeetPerDay(double billioncubicfeetperday)
#else
        public static GasRate FromBillionCubicFeetPerDay(QuantityValue billioncubicfeetperday)
#endif
        {
            double value = (double) billioncubicfeetperday;
            return new GasRate(value, GasRateUnit.BillionCubicFootPerDay);
        }

        /// <summary>
        ///     Get GasRate from CubicFeetPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromCubicFeetPerDay(double cubicfeetperday)
#else
        public static GasRate FromCubicFeetPerDay(QuantityValue cubicfeetperday)
#endif
        {
            double value = (double) cubicfeetperday;
            return new GasRate(value, GasRateUnit.CubicFootPerDay);
        }

        /// <summary>
        ///     Get GasRate from CubicKiloMetersPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromCubicKiloMetersPerDay(double cubickilometersperday)
#else
        public static GasRate FromCubicKiloMetersPerDay(QuantityValue cubickilometersperday)
#endif
        {
            double value = (double) cubickilometersperday;
            return new GasRate(value, GasRateUnit.CubicKiloMetersPerDay);
        }

        /// <summary>
        ///     Get GasRate from CubicMetersPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromCubicMetersPerDay(double cubicmetersperday)
#else
        public static GasRate FromCubicMetersPerDay(QuantityValue cubicmetersperday)
#endif
        {
            double value = (double) cubicmetersperday;
            return new GasRate(value, GasRateUnit.CubicMeterPerDay);
        }

        /// <summary>
        ///     Get GasRate from GigacubicFeetPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromGigacubicFeetPerDay(double gigacubicfeetperday)
#else
        public static GasRate FromGigacubicFeetPerDay(QuantityValue gigacubicfeetperday)
#endif
        {
            double value = (double) gigacubicfeetperday;
            return new GasRate(value, GasRateUnit.GigacubicFootPerDay);
        }

        /// <summary>
        ///     Get GasRate from HectocubicMetersPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromHectocubicMetersPerDay(double hectocubicmetersperday)
#else
        public static GasRate FromHectocubicMetersPerDay(QuantityValue hectocubicmetersperday)
#endif
        {
            double value = (double) hectocubicmetersperday;
            return new GasRate(value, GasRateUnit.HectocubicMeterPerDay);
        }

        /// <summary>
        ///     Get GasRate from KilocubicFeetPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromKilocubicFeetPerDay(double kilocubicfeetperday)
#else
        public static GasRate FromKilocubicFeetPerDay(QuantityValue kilocubicfeetperday)
#endif
        {
            double value = (double) kilocubicfeetperday;
            return new GasRate(value, GasRateUnit.KilocubicFootPerDay);
        }

        /// <summary>
        ///     Get GasRate from KilocubicMetersPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromKilocubicMetersPerDay(double kilocubicmetersperday)
#else
        public static GasRate FromKilocubicMetersPerDay(QuantityValue kilocubicmetersperday)
#endif
        {
            double value = (double) kilocubicmetersperday;
            return new GasRate(value, GasRateUnit.KilocubicMeterPerDay);
        }

        /// <summary>
        ///     Get GasRate from MegacubicFeetPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromMegacubicFeetPerDay(double megacubicfeetperday)
#else
        public static GasRate FromMegacubicFeetPerDay(QuantityValue megacubicfeetperday)
#endif
        {
            double value = (double) megacubicfeetperday;
            return new GasRate(value, GasRateUnit.MegacubicFootPerDay);
        }

        /// <summary>
        ///     Get GasRate from MegacubicMetersPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromMegacubicMetersPerDay(double megacubicmetersperday)
#else
        public static GasRate FromMegacubicMetersPerDay(QuantityValue megacubicmetersperday)
#endif
        {
            double value = (double) megacubicmetersperday;
            return new GasRate(value, GasRateUnit.MegacubicMeterPerDay);
        }

        /// <summary>
        ///     Get GasRate from MillionCubicFeetPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromMillionCubicFeetPerDay(double millioncubicfeetperday)
#else
        public static GasRate FromMillionCubicFeetPerDay(QuantityValue millioncubicfeetperday)
#endif
        {
            double value = (double) millioncubicfeetperday;
            return new GasRate(value, GasRateUnit.MillionCubicFootPerDay);
        }

        /// <summary>
        ///     Get GasRate from TeracubicFeetPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromTeracubicFeetPerDay(double teracubicfeetperday)
#else
        public static GasRate FromTeracubicFeetPerDay(QuantityValue teracubicfeetperday)
#endif
        {
            double value = (double) teracubicfeetperday;
            return new GasRate(value, GasRateUnit.TeracubicFootPerDay);
        }

        /// <summary>
        ///     Get GasRate from ThousandCubicFeetPerDay.
        /// </summary>
#if WINDOWS_UWP
        [Windows.Foundation.Metadata.DefaultOverload]
        public static GasRate FromThousandCubicFeetPerDay(double thousandcubicfeetperday)
#else
        public static GasRate FromThousandCubicFeetPerDay(QuantityValue thousandcubicfeetperday)
#endif
        {
            double value = (double) thousandcubicfeetperday;
            return new GasRate(value, GasRateUnit.ThousandCubicFootPerDay);
        }


        /// <summary>
        ///     Dynamically convert from value and unit enum <see cref="GasRateUnit" /> to <see cref="GasRate" />.
        /// </summary>
        /// <param name="value">Value to convert from.</param>
        /// <param name="fromUnit">Unit to convert from.</param>
        /// <returns>GasRate unit value.</returns>
#if WINDOWS_UWP
        // Fix name conflict with parameter "value"
        [return: System.Runtime.InteropServices.WindowsRuntime.ReturnValueName("returnValue")]
        public static GasRate From(double value, GasRateUnit fromUnit)
#else
        public static GasRate From(QuantityValue value, GasRateUnit fromUnit)
#endif
        {
            return new GasRate((double)value, fromUnit);
        }

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
        /// <returns>Unit abbreviation string.</returns>
        [UsedImplicitly]
        public static string GetAbbreviation(GasRateUnit unit)
        {
            return GetAbbreviation(unit, null);
        }

        /// <summary>
        ///     Get unit abbreviation string.
        /// </summary>
        /// <param name="unit">Unit to get abbreviation for.</param>
#if WINDOWS_UWP
        /// <param name="cultureName">Name of culture (ex: "en-US") to use for localization. Defaults to <see cref="UnitSystem" />'s default culture.</param>
#else
        /// <param name="provider">Format to use for localization. Defaults to <see cref="UnitSystem.DefaultCulture" />.</param>
#endif
        /// <returns>Unit abbreviation string.</returns>
        [UsedImplicitly]
        public static string GetAbbreviation(
          GasRateUnit unit,
#if WINDOWS_UWP
          [CanBeNull] string cultureName)
#else
          [CanBeNull] IFormatProvider provider)
#endif
        {
#if WINDOWS_UWP
            // Windows Runtime Component does not support CultureInfo and IFormatProvider types, so we use culture name for public methods: https://msdn.microsoft.com/en-us/library/br230301.aspx
            IFormatProvider provider = cultureName == null ? UnitSystem.DefaultCulture : new CultureInfo(cultureName);
#else
            provider = provider ?? UnitSystem.DefaultCulture;
#endif

            return UnitSystem.GetCached(provider).GetDefaultAbbreviation(unit);
        }

        #endregion

        #region Equality / IComparable

        public int CompareTo(object obj)
        {
            if(obj is null) throw new ArgumentNullException(nameof(obj));
            if(!(obj is GasRate)) throw new ArgumentException("Expected type GasRate.", nameof(obj));

            return CompareTo((GasRate)obj);
        }

        // Windows Runtime Component does not allow public methods/ctors with same number of parameters: https://msdn.microsoft.com/en-us/library/br230301.aspx#Overloaded methods
#if WINDOWS_UWP
        internal
#else
        public
#endif
        int CompareTo(GasRate other)
        {
            return _value.CompareTo(other.AsBaseNumericType(this.Unit));
        }

        [Obsolete("It is not safe to compare equality due to using System.Double as the internal representation. It is very easy to get slightly different values due to floating point operations. Instead use Equals($quantityName, double, ComparisonType) to provide the max allowed absolute or relative error.")]
        public override bool Equals(object obj)
        {
            if(obj is null || !(obj is GasRate))
                return false;

            var objQuantity = (GasRate)obj;
            return _value.Equals(objQuantity.AsBaseNumericType(this.Unit));
        }

        /// <summary>
        ///     <para>
        ///     Compare equality to another GasRate within the given absolute or relative tolerance.
        ///     </para>
        ///     <para>
        ///     Relative tolerance is defined as the maximum allowable absolute difference between this quantity's value and
        ///     <paramref name="other"/> as a percentage of this quantity's value. <paramref name="other"/> will be converted into
        ///     this quantity's unit for comparison. A relative tolerance of 0.01 means the absolute difference must be within +/- 1% of
        ///     this quantity's value to be considered equal.
        ///     <example>
        ///     In this example, the two quantities will be equal if the value of b is within +/- 1% of a (0.02m or 2cm).
        ///     <code>
        ///     var a = Length.FromMeters(2.0);
        ///     var b = Length.FromInches(50.0);
        ///     a.Equals(b, 0.01, ComparisonType.Relative);
        ///     </code>
        ///     </example>
        ///     </para>
        ///     <para>
        ///     Absolute tolerance is defined as the maximum allowable absolute difference between this quantity's value and
        ///     <paramref name="other"/> as a fixed number in this quantity's unit. <paramref name="other"/> will be converted into
        ///     this quantity's unit for comparison.
        ///     <example>
        ///     In this example, the two quantities will be equal if the value of b is within 0.01 of a (0.01m or 1cm).
        ///     <code>
        ///     var a = Length.FromMeters(2.0);
        ///     var b = Length.FromInches(50.0);
        ///     a.Equals(b, 0.01, ComparisonType.Absolute);
        ///     </code>
        ///     </example>
        ///     </para>
        ///     <para>
        ///     Note that it is advised against specifying zero difference, due to the nature
        ///     of floating point operations and using System.Double internally.
        ///     </para>
        /// </summary>
        /// <param name="other">The other quantity to compare to.</param>
        /// <param name="tolerance">The absolute or relative tolerance value. Must be greater than or equal to 0.</param>
        /// <param name="comparisonType">The comparison type: either relative or absolute.</param>
        /// <returns>True if the absolute difference between the two values is not greater than the specified relative or absolute tolerance.</returns>
        public bool Equals(GasRate other, double tolerance, ComparisonType comparisonType)
        {
            if(tolerance < 0)
                throw new ArgumentOutOfRangeException("tolerance", "Tolerance must be greater than or equal to 0.");

            double thisValue = (double)this.Value;
            double otherValueInThisUnits = other.As(this.Unit);

            return UnitsNet.Comparison.Equals(thisValue, otherValueInThisUnits, tolerance, comparisonType);
        }

        /// <summary>
        ///     Compare equality to another GasRate by specifying a max allowed difference.
        ///     Note that it is advised against specifying zero difference, due to the nature
        ///     of floating point operations and using System.Double internally.
        /// </summary>
        /// <param name="other">Other quantity to compare to.</param>
        /// <param name="maxError">Max error allowed.</param>
        /// <returns>True if the difference between the two values is not greater than the specified max.</returns>
        [Obsolete("Please use the Equals(GasRate, double, ComparisonType) overload. This method will be removed in a future version.")]
        public bool Equals(GasRate other, GasRate maxError)
        {
            return Math.Abs(_value - other.AsBaseNumericType(this.Unit)) <= maxError.AsBaseNumericType(this.Unit);
        }

        public override int GetHashCode()
        {
            return new { Value, Unit }.GetHashCode();
        }

        #endregion

        #region Conversion

        /// <summary>
        ///     Convert to the unit representation <paramref name="unit" />.
        /// </summary>
        /// <returns>Value converted to the specified unit.</returns>
        public double As(GasRateUnit unit)
        {
            if(Unit == unit)
                return Convert.ToDouble(Value);

            var converted = AsBaseNumericType(unit);
            return Convert.ToDouble(converted);
        }

        /// <summary>
        ///     Converts this GasRate to another GasRate with the unit representation <paramref name="unit" />.
        /// </summary>
        /// <returns>A GasRate with the specified unit.</returns>
        public GasRate ToUnit(GasRateUnit unit)
        {
            var convertedValue = AsBaseNumericType(unit);
            return new GasRate(convertedValue, unit);
        }

        /// <summary>
        ///     Converts the current value + unit to the base unit.
        ///     This is typically the first step in converting from one unit to another.
        /// </summary>
        /// <returns>The value in the base unit representation.</returns>
        private double AsBaseUnit()
        {
            switch(Unit)
            {
                case GasRateUnit.BillionCubicFootPerDay: return _value*28316800;
                case GasRateUnit.CubicFootPerDay: return _value*0.0283168;
                case GasRateUnit.CubicKiloMetersPerDay: return _value/1000;
                case GasRateUnit.CubicMeterPerDay: return _value;
                case GasRateUnit.GigacubicFootPerDay: return (_value*0.0283168) * 1e9d;
                case GasRateUnit.HectocubicMeterPerDay: return (_value) * 1e2d;
                case GasRateUnit.KilocubicFootPerDay: return (_value*0.0283168) * 1e3d;
                case GasRateUnit.KilocubicMeterPerDay: return (_value) * 1e3d;
                case GasRateUnit.MegacubicFootPerDay: return (_value*0.0283168) * 1e6d;
                case GasRateUnit.MegacubicMeterPerDay: return (_value) * 1e6d;
                case GasRateUnit.MillionCubicFootPerDay: return _value*28316.8;
                case GasRateUnit.TeracubicFootPerDay: return (_value*0.0283168) * 1e12d;
                case GasRateUnit.ThousandCubicFootPerDay: return _value*28.3168;
                default:
                    throw new NotImplementedException($"Can not convert {Unit} to base units.");
            }
        }

        private double AsBaseNumericType(GasRateUnit unit)
        {
            if(Unit == unit)
                return _value;

            var baseUnitValue = AsBaseUnit();

            switch(unit)
            {
                case GasRateUnit.BillionCubicFootPerDay: return baseUnitValue/28316800;
                case GasRateUnit.CubicFootPerDay: return baseUnitValue/0.0283168;
                case GasRateUnit.CubicKiloMetersPerDay: return baseUnitValue*1000;
                case GasRateUnit.CubicMeterPerDay: return baseUnitValue;
                case GasRateUnit.GigacubicFootPerDay: return (baseUnitValue/0.0283168) / 1e9d;
                case GasRateUnit.HectocubicMeterPerDay: return (baseUnitValue) / 1e2d;
                case GasRateUnit.KilocubicFootPerDay: return (baseUnitValue/0.0283168) / 1e3d;
                case GasRateUnit.KilocubicMeterPerDay: return (baseUnitValue) / 1e3d;
                case GasRateUnit.MegacubicFootPerDay: return (baseUnitValue/0.0283168) / 1e6d;
                case GasRateUnit.MegacubicMeterPerDay: return (baseUnitValue) / 1e6d;
                case GasRateUnit.MillionCubicFootPerDay: return baseUnitValue/28316.8;
                case GasRateUnit.TeracubicFootPerDay: return (baseUnitValue/0.0283168) / 1e12d;
                case GasRateUnit.ThousandCubicFootPerDay: return baseUnitValue/28.3168;
                default:
                    throw new NotImplementedException($"Can not convert {Unit} to {unit}.");
            }
        }

        #endregion

        #region Parsing

        /// <summary>
        ///     Parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="ArgumentException">
        ///     Expected string to have one or two pairs of quantity and unit in the format
        ///     "&lt;quantity&gt; &lt;unit&gt;". Eg. "5.5 m" or "1ft 2in"
        /// </exception>
        /// <exception cref="AmbiguousUnitParseException">
        ///     More than one unit is represented by the specified unit abbreviation.
        ///     Example: Volume.Parse("1 cup") will throw, because it can refer to any of
        ///     <see cref="VolumeUnit.MetricCup" />, <see cref="VolumeUnit.UsLegalCup" /> and <see cref="VolumeUnit.UsCustomaryCup" />.
        /// </exception>
        /// <exception cref="UnitsNetException">
        ///     If anything else goes wrong, typically due to a bug or unhandled case.
        ///     We wrap exceptions in <see cref="UnitsNetException" /> to allow you to distinguish
        ///     Units.NET exceptions from other exceptions.
        /// </exception>
        public static GasRate Parse(string str)
        {
            return Parse(str, null);
        }

        /// <summary>
        ///     Try to parse a string with one or two quantities of the format "&lt;quantity&gt; &lt;unit&gt;".
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="result">Resulting unit quantity if successful.</param>
        /// <example>
        ///     Length.Parse("5.5 m", new CultureInfo("en-US"));
        /// </example>
        public static bool TryParse([CanBeNull] string str, out GasRate result)
        {
            return TryParse(str, null, out result);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        public static GasRateUnit ParseUnit(string str)
        {
            return ParseUnit(str, (IFormatProvider)null);
        }

        /// <summary>
        ///     Parse a unit string.
        /// </summary>
        /// <param name="str">String to parse. Typically in the form: {number} {unit}</param>
        /// <param name="cultureName">Name of culture (ex: "en-US") to use when parsing number and unit. Defaults to <see cref="UnitSystem" />'s default culture.</param>
        /// <example>
        ///     Length.ParseUnit("m", new CultureInfo("en-US"));
        /// </example>
        /// <exception cref="ArgumentNullException">The value of 'str' cannot be null. </exception>
        /// <exception cref="UnitsNetException">Error parsing string.</exception>
        [Obsolete("Use overload that takes IFormatProvider instead of culture name. This method was only added to support WindowsRuntimeComponent and will be removed from other .NET targets.")]
        public static GasRateUnit ParseUnit(string str, [CanBeNull] string cultureName)
        {
            return ParseUnit(str, cultureName == null ? null : new CultureInfo(cultureName));
        }

        #endregion

        [Obsolete("This is no longer used since we will instead use the quantity's Unit value as default.")]
        /// <summary>
        ///     Set the default unit used by ToString(). Default is CubicMeterPerDay
        /// </summary>
        public static GasRateUnit ToStringDefaultUnit { get; set; } = GasRateUnit.CubicMeterPerDay;

        /// <summary>
        ///     Get default string representation of value and unit.
        /// </summary>
        /// <returns>String representation.</returns>
        public override string ToString()
        {
            return ToString(Unit);
        }

        /// <summary>
        ///     Get string representation of value and unit. Using current UI culture and two significant digits after radix.
        /// </summary>
        /// <param name="unit">Unit representation to use.</param>
        /// <returns>String representation.</returns>
        public string ToString(GasRateUnit unit)
        {
            return ToString(unit, null, 2);
        }

        /// <summary>
        /// Represents the largest possible value of GasRate
        /// </summary>
        public static GasRate MaxValue => new GasRate(double.MaxValue, BaseUnit);

        /// <summary>
        /// Represents the smallest possible value of GasRate
        /// </summary>
        public static GasRate MinValue => new GasRate(double.MinValue, BaseUnit);

        /// <summary>
        ///     The <see cref="QuantityType" /> of this quantity.
        /// </summary>
        public QuantityType Type => GasRate.QuantityType;

        /// <summary>
        ///     The <see cref="BaseDimensions" /> of this quantity.
        /// </summary>
        public BaseDimensions Dimensions => GasRate.BaseDimensions;
    }
}
